import "./style.css";

import Header from "./commons/header";
import Footer from "./commons/footer/footer";
import { Caveat } from "next/font/google";

// ⬇️ Load Caveat font, but don’t apply globally
export const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Ace360 | App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {" "}
        {/* No caveat font here */}
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// layout.js or root page.js
