import Footer from './commons/footer';
import Header from './commons/header';
import './style.css';


export const metadata = {
  title: "Sp Medifort | App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
